name: CI
on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch: # for manual runs

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12.11
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install the project
        run: uv sync --locked --all-extras
      - name: Run linters
        run: uv run pre-commit run --all-files

  test:
    name: test
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12.11
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install the project
        run: uv sync --locked --all-extras
      - name: Run unit tests
        run: uv run pytest
